# This is a basic workflow to help you get started with Actions

name: build_docker

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get repository name
        run: echo REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}') >> $GITHUB_ENV
        shell: bash
        env:
          GITHUB_REPOSITORY: ${{ github.GITHUB_REPOSITORY }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME}}
          flavor: latest=true
          # generate Docker tags based on the following events/attributes
          tags: type=schedule,pattern={{date 'YYYYMMDD'}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
